### ISSUE TITLE
"Tried to connect to each peer twice and failed" obscures real errors 

### ISSUE THREAD

**Issue by thockin** [coreos/go-etcd#185]
I have a case where etcd is returning 413.  The request code is checked for validHttpStatusCode[], which is false, so it returns the ErrCodeEtcdNotReachable error.

First, retrying in this case is pointless.

Second, by obscuring the actual error, we make the debug incredibly difficult.

Should 413 be considered valid?  Or some other fix?

**Comment by thockin** [comment]
I'm also trying to figure out where the 413 is coming from - I can write 8MB keys via etcdctl, but this is failing around 1MB.  Is there some intermediate config that I am not finding that imposes a limit?

**Comment by xiang90** [comment]
@thockin We do not set hard limit on etcd server. However, go's http server seems to have dos protection.

https://github.com/golang/go/issues/2093

**Comment by thockin** [comment]
That indicates a 10 MB limit.  with etcdctl I was able to write an 8 MB value, but I can not do that from this etcd client code.

(and the original bug still exists - this logic obscures basically all errors)

**Comment by thockin** [comment]
Any intention to fix this?  Every time we get an error that has theis string I know it is totally bogus, and we have to dig in and sprinkle crappy printfs to get a clue.

**Comment by xiang90** [comment]
@thockin etcdctl is using go-etcd. I have no idea why etcdctl works but go-etcd does not. My best guess is the limit is not only about the size. Also we set no limitation at the server side about the size.

I will try to reproduce your problem later today or tomorrow.

**Comment by thockin** [comment]
Note this bug is not specifically about the size limit, but about the fact
that the go-etcd client lib totally hides all errors and turns them into
this generic message, which is inaccurate and unhelpful.

**Comment by wb14123** [comment]
Any update on this? I get the same error and cannot figure out how to fix it.

**Comment by yichengq** [comment]
@wb14123  This has been fixed by #193 . You could checkout latest go-etcd and give it a try.

**Comment by wb14123** [comment]
@yichengq  Isn't this just add more error message? I still get the error: 

```
 502 [Request Entity Too Large] 
```

**Comment by wb14123** [comment]
OK. I understand that the request in this issue is just improve error message. But did you find the reason of 413? @thockin
